### ISSUE TITLE
Access denied when connecting to Romit

### ISSUE THREAD

**Issue by jtcoyle** [RoboCoin/robocoin-sdk-net-sample#1]

**Comment by jtcoyle** [comment]
This issue can be deleted.  When I first tried to use the Cash type API, I was getting an error and thought I needed to use the Connector type api.  My cash type api is now working.

**Comment by thallium205** [comment]
The CASH API keys are for kiosks/tablets.
The CONNECOTR API keys allow https://github.com/RoboCoin/robocoin-connector to connect to your operator wallet and monitor float and make trades as necessary.
